mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
  
    path('', include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # Other URL patterns for your project
]

polls/models.py
from django.utils import timezone
from django.db import models
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=250)
    pub_date = models.DateTimeField()

    def __str__(self):
        return f'{self.question_text}'
    
    def was_published_recently(self):
        # this method will tell me if the question was published within last 24 hours
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=1))

class Choice(models.Model):
    choice_text = models.CharField(max_length=250)
    votes = models.IntegerField(default=0)
    # question to which this particular choice is related?
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.choice_text}'

polls/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect

from polls.models import Question, Choice

def index(request):
   
    questions = Question.objects.all()
    
    context = {
        'question_list': [question for question in questions]
    }
    
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {
        'question': question
    }
    return render(request, 'polls/detail.html', context)

def results(request, question_id):
  
    question = Question.objects.get(id=question_id)
    context = {
        'question': question
    }
    return render(request, 'polls/result.html', context)


def vote(request, question_id):
    question = Question.objects.get(id=question_id)

    try:
        selected_choice = Choice.objects.get(id=request.POST["my_selection"])

    except (KeyError, Choice.DoesNotExist):
        
        return render(request, "polls/detail.html", { "question": question, "error_message": "You didn't select a choice.",},
        )
    
    else:
        selected_choice.votes += 1
        selected_choice.save()
       
        return HttpResponseRedirect(reverse("results", args=(question.id,)))

templates/polls/detail.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css.map' %}">
</head>
<body>

    <script src="{% static 'bootstrap.js' %}"></script>
  <script src="{% static 'bootstrap.js.map' %}"></script>
  <script src="{% static 'bootstrap.min.js.map' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.js.map' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js.map' %}"></script>

    <div class="content">
        <form action="{% url 'vote' question.id %}" method="post">
            {% csrf_token %}

            <h1>{{ question.question_text }}</h1>

            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            
            {% for choice in question.choice_set.all %}
                <input type="radio" name="my_selection" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}

            <input type="submit" value="Vote">
        </form>
    </div>
</body>
</html>

templates/polls/index.html
{% load static %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <style>
       
        .attraction-box {
            width: 500px;
            height: 500px;
            background-color: #f2f2f2;
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* Styling for the content inside the box */
        .attraction-title {
            font-size: 24px;
            font-weight: bold;
        }

        .attraction-description {
            font-size: 16px;
        }
    </style>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.css.map' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css.map' %}">
</head>
<body>


    <script src="{% static 'bootstrap.js' %}"></script>
  <script src="{% static 'bootstrap.js.map' %}"></script>
  <script src="{% static 'bootstrap.min.js.map' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.js.map' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js.map' %}"></script>
   <div class="attraction-box">
    <div class="attraction-description">
    {% if question_list %}
        <ul>
            {% for question in question_list %}
                <li>
                    <h2>
                    <!-- <a href="/polls/{{question.id}}">{{question.question_text}}</a> -->
                    <a href="{% url 'detail' question.id %}">{{question.question_text}}</a>
                    </h2>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available as of now, maybe you can check again later.</p>
    {% endif %}
  </div>
  </div>
</body>
</html>

templates/polls/result.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    
    <style>
       
        .attraction-box {
            width: 500px;
            height: 300px;
            background-color: #070606;
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* Styling for the content inside the box */
        .attraction-title {
            font-size: 24px;
            font-weight: bold;
        }

        .attraction-description {
            font-size: 16px;
        }
    </style>
    <link rel="stylesheet" href="{% static 'style.css' %}">
      <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap.css.map' %}">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css.map' %}">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-grid.css.map' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-grid.min.css.map' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-reboot.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-reboot.css.map' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-reboot.min.css.map' %}">
</head>
<body>
<div class="attraction-box">
    <div class="attraction-description">
  <script src="{% static 'bootstrap.js' %}"></script>
  <script src="{% static 'bootstrap.js.map' %}"></script>
  <script src="{% static 'bootstrap.min.js.map' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.js.map' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js.map' %}"></script>
    <h1> {{question.question_text}} </h1>

    <h3>    
        <ul>
            {% for choice in question.choice_set.all %}
                <li>
                    {{choice.choice_text}} - {{ choice.votes }} votes
                </li>
            {% endfor %}
        </ul>
    </h3>

    <a href="{% url 'detail' question.id %}">Vote again?</a>
    </div>
    </div>
</body>
</html>